In [1]:
#example slide

In [3]:
import numpy as np
returns = np.array([0.1, 0.08])
sigma_1 = 0.2
sigma_2 = 0.1
rho1_2 = 0.5
Rf = 0.05

In [14]:
a = np.array([returns, returns])

In [15]:
np.cov(a)

array([[0.0002, 0.0002],
       [0.0002, 0.0002]])

In [20]:
rho1_2 * sigma_1*sigma_2

0.010000000000000002

In [21]:
cov_matrix = np.zeros((2,2))
cov_matrix[0][0] = sigma_1**2
cov_matrix[0][1] = rho1_2 * sigma_1*sigma_2
cov_matrix[1][0] = rho1_2 * sigma_1*sigma_2
cov_matrix[1][1] = sigma_2**2

In [22]:
cov_matrix

array([[0.04, 0.01],
       [0.01, 0.01]])

In [68]:
final_matrix = np.zeros((3,3))

In [69]:
final_matrix[0][0] = 2*(sigma_1**2)
final_matrix[0][1] = round(2*cov_matrix[0][1], 2)
final_matrix[0][2] = -(returns[0] - Rf)

final_matrix[1][0] = 2*sigma_2**2
final_matrix[1][1] = round(2*cov_matrix[0][1], 2)
final_matrix[1][2] = -(returns[1] - Rf)

final_matrix[2][0] = returns[0] - Rf
final_matrix[2][1] = returns[1] - Rf
final_matrix[2][2] = 0

In [70]:
final_matrix

array([[ 0.08,  0.02, -0.05],
       [ 0.02,  0.02, -0.03],
       [ 0.05,  0.03,  0.  ]])

In [71]:
results = np.array([0, 0, 0.02])

In [72]:
x = np.linalg.solve(final_matrix, results)

In [73]:
x

array([0.12903226, 0.4516129 , 0.38709677])

In [78]:

# importing library sympy
from sympy import symbols, Eq, solve
x, y, l = symbols('x,y,l')
  
# defining equations
eq1 = Eq((final_matrix[0][0]*x + final_matrix[0][1]*y + final_matrix[0][2]*l), results[0])
print("Equation 1:")
print(eq1)
eq2 = Eq((final_matrix[1][0]*x + final_matrix[1][1]*y +final_matrix[1][2]*l), results[1])
print("Equation 2")
print(eq2)
eq3 = Eq((final_matrix[2][0]*x + final_matrix[2][1]*y +final_matrix[2][2]*l), results[2])
print("Equation 3")
print(eq3)
  
# solving the equation
print("Values of 2 unknown variable are as follows:")
  
print(solve((eq1, eq2,eq3), (x, y, l)))

Equation 1:
Eq(-0.05*l + 0.08*x + 0.02*y, 0.0)
Equation 2
Eq(-0.03*l + 0.02*x + 0.02*y, 0.0)
Equation 3
Eq(0.05*x + 0.03*y, 0.02)
Values of 2 unknown variable are as follows:
{x: 0.129032258064516, y: 0.451612903225806, l: 0.387096774193548}
